--- a/Makefile
+++ b/Makefile
@@ -22,7 +22,7 @@ COBJS=init.o comm.o msgs.o collcomm.o groups.o utils.o
 BYTEOBJS=mpi.cmo
 NATOBJS=$(BYTEOBJS:.cmo=.cmx)

-all: byte
+all: byte opt

 byte: libcamlmpi.a mpi.cma

@@ -32,7 +32,7 @@ libcamlmpi.a: $(COBJS)
 	$(OCAMLMKLIB) -oc camlmpi $(COBJS) -L$(MPILIBDIR) -lmpi

 install:
-	ocamlfind install mpi META mpi.mli mpi.cmi mpi.cmti \
+	ocamlfind install $(OCAMLFIND_INSTFLAGS) mpi META mpi.mli mpi.cmi mpi.cmti \
           $(wildcard mpi*.cmx) $(wildcard mpi.cm*a) \
           $(wildcard *mpi.a) $(wildcard *mpi.so)

